version: '3.4'

services:
  kubeui:
    image: harpalsgh/kubeui
    build:
      context: .
      dockerfile: KubeUI/Dockerfile
    ports:
      - 4002:80

  kubeapi:
    image: harpalsgh/kubeapi
    build:
      context: .
      dockerfile: kubeApi/Dockerfile
    ports:
      - 4001:80

