version: '3.4'

services:
  kubeui:
    image: acrkubecde.azurecr.io/kubeui:v3
    build:
      context: .
      dockerfile: KubeUI/Dockerfile
    ports:
      - 4002:80

  kubeapi:
    image: acrkubecde.azurecr.io/kubeapi:v3
    build:
      context: .
      dockerfile: kubeApi/Dockerfile
    ports:
      - 4001:80
